server:
    port: 8088
    # servlet 上下文路径，默认/ ,可以通过此方式设置上下文访问路径
    servlet:
        context-path: /
spring:
    datasource:
        name: nifengi
        #采用druid的数据源
        type: com.alibaba.druid.pool.DruidDataSource
        #连接数据库的url
        url: jdbc:mysql://192.168.1.124:3306/netty
        #驱动类
        driver-class-name: com.mysql.cj.jdbc.Driver
        #用户名
        username: root
        password: root
        #监控统计
        filters: stat
        initial-size: 2  #初始化连接
        max-idle: 10 #最大空闲连接数
        min-idle: 1  # 最小空闲连接数
        max-active: 20  #最大活动连接
        #获取连接超时的等待时间
        max-wait: 60000
        #间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-evict-runs-millis: 60000
        #一个连接在池中最小生存的空间
        min-evictable-time-millis: 300000
        #验证连接有效与否的SQL，不同的数据配置不同
        validation-query: SELECT 'x'
        #指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将被从池中去除
        test-while-idle: true
        #借出连接时不要测试，否则影响性能
        test-on-borrow: false
    # springmvc 视图解析器扫描前缀与后缀为指定名称的路径
    mvc:
        view:
            prefix: /WEB-INF/pages/
            suffix: .jsp

mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.nifengi.www.netty.mybatis.entity

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
#fdfs:
#    so-timeout: 1501
#    connect-timeout: 601
#    thumb-image:             #缩略图生成参数
#        width: 150
#        height: 150
#    tracker-list:            #TrackerList参数,支持多个
#        - 172.17.9.194:22122


minio:
    address: http://192.168.1.124:9010
    access: minioadmin
    secret: minioadmin
    bucket: netty